name: Maximilano Rios
title: Maximiliano Rios
lightavatar: /assets/images/tired.png
darkavatar: /assets/images/tired.png
tagline:
description:
url:
baseurl: ""
author: maxrios
logo: /assets/images/light_bauhaus_logo.png

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-78X9LZN5TZ
permalink: /:year/:month/:day/:title/
footer-links:
  email: max@maxrios.dev
  github: maxrios
  linkedin: maximiliano-merced
  rss: maxrios
  bsky: maxrios.dev

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      pinned: false
